### PR TITLE
Add eslint rule to remind people to favour components instead of others

### PR DESCRIPTION
**Pull request by maxparm**
### Description

Add rule to show an error or warning when a component should be used instead of an other.

`Icon2` instead of `Icon` for example.

### Test

- [ ] Code looks good
- [ ] Tests look good

### CODE REVIEW

**Comment by maxparm** [comment]
Readayyy for CR.

**Comment by haffmaestro** [comment]
Niiiice

**Comment by himynameisdave** [comment]
Why not just use [this existing rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-deprecated.md) to mark specific components as deprecated? 

We could configure it to only be a warning, so that we don't have to go back and change all the uses of deprecated components, but so that we'd at least get some visibility in our editors that components have been deprecated.

**Comment by maxparm** [comment]
But that seems specific to react methods of oldest versions. I created this rule for us internally to mark common components that are deprecated and show the ones to use instead.

**Comment by himynameisdave** [comment]
Sorry Max I think I linked to the wrong thing.

[This is the plugin/rule that I meant to link to](https://github.com/AlexMost/eslint-plugin-deprecate/blob/master/docs/rules/import.md). Maybe not worth adding it as a whole new plugin, but it might be good to at least look at that one is doing if you need some inspiration.

**Comment by maxparm** [comment]
Ah yes that does the same thing!

**Comment by maxparm** [comment]
So I guess we would add that rule directly in https://github.com/7Geese/eslint-config-7geese right?

**Comment by himynameisdave** [comment]
@maxparm yeah we could just add that plugin, configure it in our repo then start using it 👍

**Pull request closed without merging**
